### ISSUE TITLE
non-hero People

### ISSUE THREAD

**Issue by damonmc** [gever/bwx-adventure#10]
The world would be more interesting if it supported people other than the hero (who could potentially pick things up, drop them, move, say things, etc.).  Brings up a host of issues, including the need to be able to say things to the person...

**Comment by mcapraro** [comment]
this is somewhat handled by Robot and Pet. can robot be a person, @jplevyak @royseto ?

**Comment by alambeth** [comment]
I think we have this covered now with Robots, Animals, Pets, and any derivative classes the game developers want to make.
