### ISSUE TITLE
Need smarter handling of verbs on actors

### ISSUE THREAD

**Issue by gever** [gever/bwx-adventure#17]
Try 'take Fido' when standing at the front door and you will see:
```
> take Fido
You can't take the Fido.
Fido can't take the Fido.
Cat can't take the Fido.
Robby can't take the Fido.
You can't take the Fido.
> 
```
I think this makes the case for more direct control of the pets and robots. Maybe something like:
```
>tell Robby: take Fido
Robby picks up Fido gently.
>
```

**Comment by eah13** [comment]
@alambeth I'm an interloper here but love this project.  A potential solution: Take defaults to the Hero but if it fails checks if others nearby could do this instead.

When you fail to take the object, the looping through other actors could still happen, but not print the state, just update  `someone_else_can_take = True` when it finds a match.

When false:
```
> take Fido
You can't take the Fido.
It doesn't look like anyone else here can either.
> 
```

When true:
```
> take Fido
You can't take the Fido.
It seems like someone else here might be able to, though.
> 
```

Depending on how complicated you want it, it could suggest which actor to try next.  

When true:
```
> take Fido
You can't take the Fido.
It seems like Robby might be able to, though.
> 
```

**Comment by mcapraro** [comment]
i like this!

**Comment by alambeth** [comment]
yes, great suggestion, Elliot.  I'll work on adding something like this.

**Comment by alambeth** [comment]
actually John's recent changes to verb handling take care of this nicely I think
