### ISSUE TITLE
License

### ISSUE THREAD

**Issue by eah13** [gever/bwx-adventure#20]
All great open source projects deserve a great open source license.

May I suggest an MIT license and a "Contributions are welcome! Open an Issue or a pull request." addition to the README? Or should I drop them in a pull request?  I am unsure :)

**Comment by royseto** [comment]
I like the MIT license too. @gever what do you think?

**Comment by gever** [comment]
I haven't really kept up with the evolution of licenses since I left Adobe some years ago, so I'd go with your recommendation, @royseto and @eah13 :-)

**Comment by royseto** [comment]
Done. I see the MIT license a lot these days. It is fairly permissive: basically, do what you want with this, but don't remove the license and attribution, and don't sue us.

http://en.wikipedia.org/wiki/MIT_License

@gever @eah13

**Comment by gever** [comment]
That sounds perfect. We should also include a brightworks link in there :-)

On Sun, Jan 4, 2015 at 6:59 PM, Roy Seto <notifications@github.com> wrote:

> Done. I see the MIT license a lot these days. It is fairly permissive:
> basically, do what you want with this, but don't remove the license and
> attribution, and don't sue us.
>
> http://en.wikipedia.org/wiki/MIT_License
>
> @gever <https://github.com/gever> @eah13 <https://github.com/eah13>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gever/bwx-adventure/issues/20#issuecomment-68663131>.
>



-- 
Gever Tulley, Founder, Education Architect
Brightworks: An Extraordinary School
Tinkering School: Think, Make, Tinker
(415) 701-8700 | sfbrightworks.org | cell: (415) 218-0812

**Comment by royseto** [comment]
@gever great idea. The first line of the LICENSE file now reads:

    Copyright (c) 2014-2015 Gever Tulley, Brightworks (sfbrightworks.org)
